var Englishworddic = 
[
"workdays",
"working days",
"shipment point",
"shipping point",
"pick / pack time",
"factory calendar",
"plant maintenance",
"Authorization administration",
"authorization management",
"access management",
"aprocess rights",
"route",
"transit time",
"transit period",
"daily work",
"daily tasks",
"authorization role",
"company code",
"to lock",
"to disable ",
"to deactivate",
"to block",
"to unlock",
"to enable",
"to activate",
"to unblock",
"maternity protection",
"maternity leave",
"parental Leave",
"infotype",
"additional costs",
"extra charges",
"extra costs",
"surcharges",
"article ",
"item",
"assortment",
"presentation",
"shoe prepacks",
"generic articles",
"prepack (reference given in Accenture-Magna glossary)",
"inbound delivery",
"outbound delivery",
"packaging / packing",
"pack",
"unpack",
"repack",
"merchandise grouping",
"to reverse",
"to cancel",
"notification file",
"EDI (electronic data interchange)",
"UAM",
"blocked sales and distribution documents",
"phrase merging",
"reassign",
"spool requests",
"end user rights",
"characteristics",
"features",
"termination",
"material number",
"default printer ",
"standard printer",
"storage bin",
"counting",
"reversal ",
"cancel",
"movement type",
"inspection lot",
"batch",
"lot",
"counting rule",
"access violation",
"memory",
"memory consumption",
"memory consumption display",
"repeating group",
"communication channel",
"Please reset the password",
"reversing documents",
"Document cannot be reversed",
"costing variants",
"control parameter",
"background job",
"to schedule",
"creation profile",
"to make entries",
"role distribution",
"role allocation",
"role assignment",
"execution",
"implementation",
"introduction",
"implementation guide",
"EAN (European Article Number)(also called International Article Number)",
"merchandise logistics",
"number assignment",
"size category",
"Sched. Line",
"DepReq",
"valuation",
"special stock number",
"OU (order unit)",
"unrestricted use",
"message",
"No schedule lines are due for delivery until the selected date.",
"corporate structure",
"material master records",
"period initialization",
"period closing",
"distribution",
"transfer",
"transfer and distribution of material master data",
"enhancement",
"ordering (order handling)",
"inventory management",
"invoice verification",
"order processing",
"production control",
"work preparation (work scheduling)",
"exchange of messages (messaging)",
"loosely-linked",
"application services",
"distribution services",
"communication services",
"remote system",
"planning calendar",
"house bill of lading",
"laytime",
"demurrage",
"laytime calculation",
"lighterage",
"update",
"nomination",
"reference document update ",
"maintenance authorization",
"line item list",
"financial statement versions",
"G/L account postings",
"posting periods",
"reporting procedure",
"notification process",
"registration procedure",
"messaging process",
"developer key",
"MRP controller name",
"derivation rule",
"message number",
"characteristic derivation",
"revenue element",
"source values",
"target values",
"derivation rule-entry",
"source field values",
"procedure",
"transaction ",
"process",
"derivation strategy",
"reassignment",
"closing operations",
"local authorities",
"Human Resources (HR)",
"funds management",
"commitment items",
"account assignment elements",
"WBS (work breakdown structure)",
"funds centers",
"account assignment derivation",
"similarity of names",
"name parity",
"name equality",
"sub account",
"composite role",
"time management",
"bank data medium",
"employee sub group",
"analyses",
"part number"
];