var Germanworddic = 
[
"Arbeitstage",
"Arbeitstage",
"Versandstelle",
"Versandstelle",
"Richtzeit",
"Fabrikkalender",
"Instandhaltung",
"Berechtigungsverwaltung",
"Berechtigungsverwaltung",
"Berechtigungsverwaltung",
"Prozessrechte",
"Route",
"Transitzeitraum",
"Transitzeitraum",
"Tägliche Arbeiten",
"Tägliche Arbeiten",
"Berechtigungsrolle",
"Buchungskreis",
"sperren",
"sperren",
"sperren",
"sperren",
"entsperren",
"entsperren",
"entsperren",
"entsperren",
"Mutterschutz",
"Mutterschutz",
"Erziehungsurlaub",
"Infotyp",
"Mehrkosten",
"Mehrkosten",
"Mehrkosten",
"Mehrkosten",
"Artikel",
"Artikel",
"Sortiment",
"Aufmachung",
"Schuh-Lot",
"Sammelartikel",
"Lot",
"Anlieferung",
"Auslieferung",
"Verpackung",
"Einpacken",
"Auspacken",
"Umpacken",
"Warengruppierung",
"stornieren",
"stornieren",
"Meldedatei",
"DFÜ (Datenfremdübertragung)",
"BBV",
"gesperrte Belege ",
"Phrasenabmischung",
"Neuvergabe",
"Spoolaufträge",
"Endbenutzerrechte",
"Merkmale",
"Merkmale",
"Abbruch",
"Materialnummer",
"Standarddrucker",
"Standarddrucker",
"Lagerplatz",
"Zählung",
"Storno",
"Storno",
"Bewegungsart",
"Prüflos",
"Charge",
"Los",
"Auszählungsregelung",
"Zugriffsverletzung",
"Speicher",
"Speicherverbrauch",
"Speicherverbrauchsanzeige",
"Wiederholungsgruppe",
"Kommunikationskanal",
"bitte Passwort zurücksetzen",
"Storno eines Belegs",
"Beleg kann nicht storniert werden",
"Kalkulationsvarianten",
"Steuerungsparameter",
"Hintergrundjob",
"einplanen",
"Erstellungsprofil",
"Eingaben durchführen",
"Rollenverteilung",
"Rollenverteilung",
"Rollenverteilung",
"Einführung",
"Einführung",
"Einführung",
"Einführungsleitfaden",
"EAN (Europäischen Artikelnumerierung)",
"Warenlogistik",
"Nummernvergabe",
"Größenkategorie",
"LpEint",
"SekBed",
"Bewertung",
"Sonderbestandsnummer",
"Bestellung Mengeneinheit (BME)",
"frei verwendbar",
"Meldungstext",
"Bis zum ausgewählten Datum sind keine Einteilungen zur Lieferung fällig.",
"Unternehmensstruktur",
"Materialstammsatz",
"Periodeninitialisierung",
"Periodenverschiebung",
"Verteilung",
"Übernahme",
"Übernahme und Verteilung von Materialstammdaten",
"Erweiterung",
"Bestellabwicklung",
"Bestandsführung",
"Rechnungsprüfung",
"Auftragsabwicklung",
"Produktionssteuerung",
"Arbeitsvorbereitung",
"Nachrichtenaustausch",
"lose gekoppelt",
"Anwendungsdienste",
"Verteilungsdienste",
"Kommunikationsdienste",
"Entferntes System",
"Einplanungskalender",
"Hausfrachtbrief",
"Liegezeit",
"Überliegegeld",
"Liegezeitberechnung",
"Leichtern",
"verbuchen",
"Planungsbeleg",
"Referenzbelegfortschreibung",
"Pflegeberechtigung",
"Einzelpostenliste",
"Bilanz/GuV",
"Sachkontenbuchung",
"Buchungsperioden",
"Meldeverfahren",
"Meldeverfahren",
"Meldeverfahren",
"Meldeverfahren",
"Entwicklerschlüssel",
"Disponentenname",
"Ableitungsregel",
"Meldungsnummer ",
"Merkmalsableitung",
"Erlösart",
"Quellwerte",
"Zielwerte",
"Ableitungsregel-Eintrag",
"Quellfeldwerte",
"Vorgehen",
"Vorgehen",
"Vorgehen",
"Ableitungsstrategie",
"Umkontierung",
"Abschlussarbeiten",
"Kommunen",
"Personalwirtschaft",
"Haushaltsmanagement",
"Finanzposition",
"Kontierungselement",
"PSP (Projektstrukturplan)",
"Finanzstellen",
"Kontierungsableitung",
"Namensgleichheit",
"Namensgleichheit",
"Namensgleichheit",
"Unterkonto",
"Sammelrolle",
"Zeitwirtschaft",
"Bankdatenträger",
"Mitarbeiterkreis",
"Auswertungen",
"Teilenummer"
];